title: VN ELLIOTT
tagline: Giao dịch chuyên sâu với lý thuyết Sóng Elliott.
tel: 0969202820
description: >- # this means to ignore newlines until "baseurl:"
  Kênh chia sẻ kiến thức về sóng ELLIOTT, thị trường tài chính: Forex, Chứng khoán quốc tế, chứng khoáng Việt nam, hàng hóa, vàng bạc và phái sinh.
baseurl: "/vn-elliott" # the subpath of your site, e.g. /blog
url: "https://haonvpt.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
timezone: "Asia/Ho_Chi_Minh"
lang: "vn-vi"
author: "Viet Cuong"
email: "vietcuong@gmail.com"
author_avatar: "/assets/images/logos/vn-elliott-logo-192-192.png"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-loading-lazy
kramdown:
  input: GFM
  toc_levels: 2..3  # Chỉ lấy h2 và h3
  
collections:
  review_items:
    output: false        # Không tạo trang html riêng cho từng item
    directory: _review_items # Tên thư mục chứa file

    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
#exclude:
#   - .sass-cache/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
